### ISSUE TITLE
Can't install with pip

### ISSUE THREAD

**Issue by a4fr** [woodmac/faust-prometheus#16]
I ran `pip3 install faustprometheus` and raise an error because there is no requirements.txt. I think the archive file in the PyPI repository is old.
```
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-dw8pemzv/faustprometheus/setup.py'"'"'; __file__='"'"'/tmp/pip-install-dw8pemzv/faustprometheus/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-dw8pemzv/faustprometheus/pip-egg-info
         cwd: /tmp/pip-install-dw8pemzv/faustprometheus/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-dw8pemzv/faustprometheus/setup.py", line 3, in <module>
        with open('requirements.txt') as fp:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by skecskes** [comment]
this should be fixed now in latest version 0.0.6
